# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-service
  annotations:
    github.com/project-slug: SoykatAmin/inventory-service   # links GitHub
    backstage.io/kubernetes-id: inventory-service          # links K8s resources
spec:
  type: service
  lifecycle: production
  owner: group:platform-team
  system: ecommerce
